export default [
  {
    encounterId: 5261153,
    orderId: 100,
    specimenType: 'Serum',
    specimenTypeModifier: 'Fasting',
    date: '',
    time: '',
    specimenSite: 'Arm',
    specimenSiteModifier: 'R',
    specimenContainer: 'Red Submission Container/Tube',
    method: 'VENI',
    volume: 0.5,
    volumeUnits: 'ml',
    specimenRole: 'P'
  },
  {
    encounterId: 5261153,
    orderId: 200,
    specimenType: 'Whole Blood',
    specimenTypeModifier: '',
    date: '',
    time: '',
    specimenSite: 'Arm',
    specimenSiteModifier: 'R',
    specimenContainer: 'Lavender Top (K2 EDTA) tube',
    method: 'VENI',
    volume: 3.0,
    volumeUnits: 'ml',
    specimenRole: 'P'
  },
  {
    encounterId: 4005507,
    orderId: 100,
    specimenType: 'Whole Blood',
    specimenTypeModifier: '',
    date: '',
    time: '',
    specimenSite: 'Arm',
    specimenSiteModifier: 'R',
    specimenContainer: 'STCUP',
    method: '',
    volume: 30.0,
    volumeUnits: 'ml',
    specimenRole: 'P'
  },
  {
    encounterId: 4005508,
    orderId: 400,
    specimenType: 'Urn',
    specimenTypeModifier: 'Fasting',
    date: '',
    time: '',
    specimenSite: 'Cath',
    specimenSiteModifier: '',
    specimenContainer: 'STCUP',
    method: '',
    volume: 30.0,
    volumeUnits: 'ml',
    specimenRole: 'P'
  },
  {
    encounterId: 4005509,
    orderId: 100,
    specimenType: 'Serum',
    specimenTypeModifier: 'Fasting',
    date: '',
    time: '',
    specimenSite: 'Arm',
    specimenSiteModifier: 'R',
    specimenContainer: 'Blue Submission Container/Tube',
    method: 'VENI',
    volume: 0.55,
    volumeUnits: 'ml',
    specimenRole: 'P'
  },
  {
    encounterId: 4005510,
    orderId: 100,
    specimenType: 'Whole Blood',
    specimenTypeModifier: '',
    date: '',
    time: '',
    specimenSite: 'Arm',
    specimenSiteModifier: 'R',
    specimenContainer: 'Magenta Top (K2 EDTA) tube',
    method: 'VENI',
    volume: 10,
    volumeUnits: 'ml',
    specimenRole: 'P'
  }
];
