export default [
  {
    encounterId: 1,
    orderId: 1,
    specimenType: 'Serum',
    specimenTypeModifier: 'Fasting',
    date: '2020-11-05',
    time: '16:15:00',
    specimenSite: 'Arm',
    specimenSiteModifier: 'R',
    specimenContainer: 'Red Submission Container/Tube',
    method: 'VENI',
    volume: 0.5,
    volumeUnits: 'ml',
    specimenRole: 'P'
  },
  {
    encounterId: 1,
    orderId: 2,
    specimenType: 'Whole Blood',
    specimenTypeModifier: '',
    date: '2020-11-05',
    time: '17:15:00',
    specimenSite: 'Arm',
    specimenSiteModifier: 'R',
    specimenContainer: 'Lavender Top (K2 EDTA) tube',
    method: 'VENI',
    volume: 3.0,
    volumeUnits: 'ml',
    specimenRole: 'P'
  },
  {
    encounterId: 2,
    orderId: 3,
    specimenType: 'Urin',
    specimenTypeModifier: 'Fasting',
    date: '2020-11-06',
    time: '08:15:00',
    specimenSite: 'Cath',
    specimenSiteModifier: '',
    specimenContainer: 'STCUP',
    method: '',
    volume: 30.0,
    volumeUnits: 'ml',
    specimenRole: 'P'
  },
  {
    encounterId: 4,
    orderId: 4,
    specimenType: 'Serum',
    specimenTypeModifier: '',
    date: '2020-11-06',
    time: '09:15:00',
    specimenSite: 'Arm',
    specimenSiteModifier: 'R',
    specimenContainer: 'Cyan Top (K2 EDTA) tube',
    method: 'VENI',
    volume: 5.0,
    volumeUnits: 'ml',
    specimenRole: 'P'
  },
  {
    encounterId: 4,
    orderId: 5,
    specimenType: 'Serum',
    specimenTypeModifier: 'Fasting',
    date: '2020-11-06',
    time: '10:15:00',
    specimenSite: 'Arm',
    specimenSiteModifier: 'R',
    specimenContainer: 'Blue Submission Container/Tube',
    method: 'VENI',
    volume: 0.55,
    volumeUnits: 'ml',
    specimenRole: 'P'
  },
  {
    encounterId: 5,
    orderId: 6,
    specimenType: 'Whole Blood',
    specimenTypeModifier: '',
    date: '2020-11-06',
    time: '11:15:00',
    specimenSite: 'Arm',
    specimenSiteModifier: 'R',
    specimenContainer: 'Magenta Top (K2 EDTA) tube',
    method: 'VENI',
    volume: 10,
    volumeUnits: 'ml',
    specimenRole: 'P'
  }
];
